services:
    - type: web
      name: flixquest-api-cuevana
      env: node
      plan: free
      buildCommand: npm install && npm run build
      startCommand: npm start
      envVars:
          - key: PORT
            value: 3000
          - key: TMDB_KEY
            sync: false
